export const BUTTON_SIZES: Record<'xsmall' | 'small' | 'medium' | 'large' | 'xlarge', string[]> = {
  xsmall: ['px-3', 'py-1', 'text-xs'],
  small: ['px-4', 'py-1.5', 'text-sm'],
  medium: ['px-5', 'py-2', 'text-base'],
  large: ['px-6', 'py-2.5', 'text-lg'],
  xlarge: ['px-7', 'py-3', 'text-xl'],
};

export const BASE_CLASSES: string[] = [
  'transition-all',
  'duration-300',
  'ease-in-out',
  'motion-reduce:transition-none',
  'font-normal',
  'focus:outline-none',
  'focus:ring-2',
  'focus:ring-offset-2',
  'focus:ring-opacity-75',
];

export const BUTTON_HOST_ATTRIBUTES: string[] = [
  'nova-tw-button',
  'nova-tw-outline-button',
  'nova-tw-flat-button',
  'nova-tw-raised-button',
  'nova-tw-stroke-button',
];

export const BUTTON_HOST_ATTRIBUTES_CLASSES: Record<string, string[]> = {
  'nova-tw-button': ['border', 'border-solid'],
  'nova-tw-outline-button': ['bg-transparent', 'border', 'border-solid'],
  'nova-tw-flat-button': ['border', 'border-solid'],
  'nova-tw-raised-button': ['shadow-md', 'hover:shadow-lg'],
  'nova-tw-stroke-button': ['bg-transparent', 'border', 'border-2'],
};

export const BUTTON_BACKGROUND_PALETTE: Record<string, string[]> = {
  black: ['bg-black'],
  white: ['bg-white'],
  slate: ['bg-slate-500'],
  gray: ['bg-gray-500'],
  zinc: ['bg-zinc-500'],
  neutral: ['bg-neutral-500'],
  stone: ['bg-stone-500'],
  red: ['bg-red-500'],
  orange: ['bg-orange-500'],
  amber: ['bg-amber-500'],
  yellow: ['bg-yellow-500'],
  lime: ['bg-lime-500'],
  green: ['bg-green-500'],
  emerald: ['bg-emerald-500'],
  teal: ['bg-teal-500'],
  cyan: ['bg-cyan-500'],
  sky: ['bg-sky-500'],
  blue: ['bg-blue-500'],
  indigo: ['bg-indigo-500'],
  violet: ['bg-violet-500'],
  purple: ['bg-purple-500'],
  fuchsia: ['bg-fuchsia-500'],
  pink: ['bg-pink-500'],
  rose: ['bg-rose-500'],
};

export const BUTTON_TEXT_PALETTE: Record<string, string[]> = {
  black: ['text-white'],
  white: ['text-black'],
  slate: ['text-slate-500'],
  gray: ['text-gray-500'],
  zinc: ['text-zinc-500'],
  neutral: ['text-neutral-500'],
  stone: ['text-stone-500'],
  red: ['text-red-500'],
  orange: ['text-orange-500'],
  amber: ['text-amber-500'],
  yellow: ['text-yellow-500'],
  lime: ['text-lime-500'],
  green: ['text-green-500'],
  emerald: ['text-emerald-500'],
  teal: ['text-teal-500'],
  cyan: ['text-cyan-500'],
  sky: ['text-sky-500'],
  blue: ['text-blue-500'],
  indigo: ['text-indigo-500'],
  violet: ['text-violet-500'],
  purple: ['text-purple-500'],
  fuchsia: ['text-fuchsia-500'],
  pink: ['text-pink-500'],
  rose: ['text-rose-500'],
};

export const BUTTON_BORDER_PALETTE: Record<string, string[]> = {
  black: ['border-black'],
  white: ['border-gray-300'],
  slate: ['border-slate-500'],
  gray: ['border-gray-500'],
  zinc: ['border-zinc-500'],
  neutral: ['border-neutral-500'],
  stone: ['border-stone-500'],
  red: ['border-red-500'],
  orange: ['border-orange-500'],
  amber: ['border-amber-500'],
  yellow: ['border-yellow-500'],
  lime: ['border-lime-500'],
  green: ['border-green-500'],
  emerald: ['border-emerald-500'],
  teal: ['border-teal-500'],
  cyan: ['border-cyan-500'],
  sky: ['border-sky-500'],
  blue: ['border-blue-500'],
  indigo: ['border-indigo-500'],
  violet: ['border-violet-500'],
  purple: ['border-purple-500'],
  fuchsia: ['border-fuchsia-500'],
  pink: ['border-pink-500'],
  rose: ['border-rose-500'],
};

export const BUTTON_HOVER_PALETTE: Record<string, string[]> = {
  black: ['hover:bg-gray-900'],
  white: ['hover:bg-gray-100'],
  slate: ['hover:bg-slate-600'],
  gray: ['hover:bg-gray-600'],
  zinc: ['hover:bg-zinc-600'],
  neutral: ['hover:bg-neutral-600'],
  stone: ['hover:bg-stone-600'],
  red: ['hover:bg-red-600'],
  orange: ['hover:bg-orange-600'],
  amber: ['hover:bg-amber-600'],
  yellow: ['hover:bg-yellow-600'],
  lime: ['hover:bg-lime-600'],
  green: ['hover:bg-green-600'],
  emerald: ['hover:bg-emerald-600'],
  teal: ['hover:bg-teal-600'],
  cyan: ['hover:bg-cyan-600'],
  sky: ['hover:bg-sky-600'],
  blue: ['hover:bg-blue-600'],
  indigo: ['hover:bg-indigo-600'],
  violet: ['hover:bg-violet-600'],
  purple: ['hover:bg-purple-600'],
  fuchsia: ['hover:bg-fuchsia-600'],
  pink: ['hover:bg-pink-600'],
  rose: ['hover:bg-rose-600'],
};

export const BUTTON_ACTIVE_PALETTE: Record<string, string[]> = {
  black: ['active:bg-gray-900'],
  white: ['active:bg-gray-100'],
  slate: ['active:bg-slate-600'],
  gray: ['active:bg-gray-600'],
  zinc: ['active:bg-zinc-600'],
  neutral: ['active:bg-neutral-600'],
  stone: ['active:bg-stone-600'],
  red: ['active:bg-red-600'],
  orange: ['active:bg-orange-600'],
  amber: ['active:bg-amber-600'],
  yellow: ['active:bg-yellow-600'],
  lime: ['active:bg-lime-600'],
  green: ['active:bg-green-600'],
  emerald: ['active:bg-emerald-600'],
  teal: ['active:bg-teal-600'],
  cyan: ['active:bg-cyan-600'],
  sky: ['active:bg-sky-600'],
  blue: ['active:bg-blue-600'],
  indigo: ['active:bg-indigo-600'],
  violet: ['active:bg-violet-600'],
  purple: ['active:bg-purple-600'],
  fuchsia: ['active:bg-fuchsia-600'],
  pink: ['active:bg-pink-600'],
  rose: ['active:bg-rose-600'],
};

export const BUTTON_FOCUS_PALETTE: Record<string, string[]> = {
  black: ['focus:border-black', 'focus:ring-black'],
  white: ['focus:border-gray-200', 'focus:ring-gray-200'],
  slate: ['focus:border-slate-600', 'focus:ring-slate-600'],
  gray: ['focus:border-gray-500', 'focus:ring-gray-600'],
  zinc: ['focus:border-zinc-500', 'focus:ring-zinc-600'],
  neutral: ['focus:border-neutral-500', 'focus:ring-neutral-600'],
  stone: ['focus:border-stone-500', 'focus:ring-stone-600'],
  red: ['focus:border-red-500', 'focus:ring-red-600'],
  orange: ['focus:border-orange-500', 'focus:ring-orange-500'],
  amber: ['focus:border-amber-500', 'focus:ring-amber-600'],
  yellow: ['focus:border-yellow-500', 'focus:ring-yellow-600'],
  lime: ['focus:border-lime-500', 'focus:ring-lime-600'],
  green: ['focus:border-green-500', 'focus:ring-green-600'],
  emerald: ['focus:border-emerald-500', 'focus:ring-emerald-600'],
  teal: ['focus:border-teal-500', 'focus:ring-teal-600'],
  cyan: ['focus:border-cyan-500', 'focus:ring-cyan-600'],
  sky: ['focus:border-sky-500', 'focus:ring-sky-600'],
  blue: ['focus:border-blue-500', 'focus:ring-blue-600'],
  indigo: ['focus:border-indigo-500', 'focus:ring-indigo-600'],
  violet: ['focus:border-violet-500', 'focus:ring-violet-600'],
  purple: ['focus:border-purple-500', 'focus:ring-purple-600'],
  fuchsia: ['focus:border-fuchsia-500', 'focus:ring-fuchsia-600'],
  pink: ['focus:border-pink-500', 'focus:ring-pink-600'],
  rose: ['focus:border-rose-500', 'focus:ring-rose-600'],
};
